from enum import Enum
from typing import Annotated, Type

from casadi import MX
from pint import Quantity

class VarSpec: ...
class VariableHints: ...
class OtherVariables(Enum): ...
class ThermoVariables(Enum): ...

class ThermoHints(VariableHints):
    def __init__(self, prefix: str): ...
    @property
    def Entropy(self) -> Type[Annotated[MX | Quantity, VarSpec]]: ...
    @property
    def Pressure(self) -> Type[Annotated[MX | Quantity, VarSpec]]: ...
    @property
    def Enthalpy(self) -> Type[Annotated[MX | Quantity, VarSpec]]: ...
    @property
    def Temperature(self) -> Type[Annotated[MX | Quantity, VarSpec]]: ...

class OtherHints(VariableHints):
    def __init__(self, prefix: str): ...
    @property
    def V_mag(self) -> Type[Annotated[MX | Quantity, VarSpec]]: ...
    @property
    def V_tan(self) -> Type[Annotated[MX | Quantity, VarSpec]]: ...
    @property
    def V_mer(self) -> Type[Annotated[MX | Quantity, VarSpec]]: ...
    @property
    def W_mag(self) -> Type[Annotated[MX | Quantity, VarSpec]]: ...
    @property
    def W_tan(self) -> Type[Annotated[MX | Quantity, VarSpec]]: ...
    @property
    def W_mer(self) -> Type[Annotated[MX | Quantity, VarSpec]]: ...

class NodeHints:
    def __init__(self, index: int): ...
    @property
    def rlt(self) -> ThermoHints: ...
    @property
    def stc(self) -> ThermoHints: ...
    @property
    def tot(self) -> ThermoHints: ...
