from enum import Enum
from typing import Annotated

from casadi import MX
from pint import Quantity

class VarSpec:
    def __init__(self, symbol: str, description: str, unit: str): ...
    @property
    def symbol(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def unit(self) -> str: ...

class VariableHints: ...
class OtherVariables(Enum): ...
class ThermoVariables(Enum): ...

class ThermoHints(VariableHints):
    def __init__(self, prefix: str, postfix: str): ...
    Entropy = Annotated[MX | Quantity, VarSpec]
    Pressure = Annotated[MX | Quantity, VarSpec]
    Enthalpy = Annotated[MX | Quantity, VarSpec]
    Temperature = Annotated[MX | Quantity, VarSpec]

class OtherHints(VariableHints):
    def __init__(self, postfix: str): ...
    V_mag = Annotated[MX | Quantity, VarSpec]
    V_tan = Annotated[MX | Quantity, VarSpec]
    V_mer = Annotated[MX | Quantity, VarSpec]
    W_mag = Annotated[MX | Quantity, VarSpec]
    W_tan = Annotated[MX | Quantity, VarSpec]
    W_mer = Annotated[MX | Quantity, VarSpec]

class NodeHints(OtherHints):
    def __init__(self, index: int): ...
    @property
    def stc(self) -> ThermoHints: ...
    @property
    def tot(self) -> ThermoHints: ...
    @property
    def rlt(self) -> ThermoHints: ...
