from pint import Quantity
from typing import Annotated
from casadi import MX
from dataclasses import dataclass
from enum import Enum

DEF_NODE: int

class NodeStates(Enum):
    STATIC = 'stc_'
    TOTAL = 'tot_'
    RELTOT = 'rlt_'

@dataclass(frozen=True, eq=False)
class VarSpec:
    symbol: str
    unit: str
    guess: float | None = ...
    bounds: tuple[float, float] | None = ...
    node: int = ...
    scalar: bool = ...
    state: None | NodeStates = ...

    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def _at_node(self, node: int) -> 'VarSpec': ...
    def _with_state(self, state: NodeStates | None) -> 'VarSpec': ...
    def _with_bounds(self, bounds: tuple[float, float] | None) -> 'VarSpec': ...
    def _with_guess(self, guess: float | None) -> 'VarSpec': ...
    def _with_symbol(self, symbol: str | None) -> 'VarSpec': ...
    def full_symbol(self, index: bool = False) -> str: ...
    @property
    def Glob(self) -> 'VarSpec': ...
    Hint = Annotated[MX | Quantity, 'VarSpec']
